import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, readFile, rm, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { once } from "node:events";
import { createServer } from "node:net";

test("fresh CLI installation from unrelated cwd admits a fake goal and records verified completion", { timeout: 40000 }, async t => {
  const root = await mkdtemp(join(tmpdir(), "mc-fresh-install-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const cli = resolve(process.env.MISSIONCONTROL_TEST_CLI || "dist/cli.js"), configDir = join(root, "config"), state = join(root, "state"), secrets = join(root, "secrets"), cwd = join(root, "elsewhere");
  await mkdir(cwd);
  const exec = promisify(execFile), env = { PATH: process.env.PATH, HOME: root };
  const run = (...args: string[]) => exec(process.execPath, [cli, "--config-dir", configDir, ...args], { cwd, env });
  const initialized = JSON.parse((await run("init", "--state-dir", state, "--secrets-dir", secrets, "--example")).stdout);
  assert.equal(initialized.example.projectId, "synthetic");
  await run("doctor");
  const portProbe = createServer(); portProbe.listen(0, "127.0.0.1"); await once(portProbe, "listening");
  const port = (portProbe.address() as { port: number }).port; await new Promise<void>(r => portProbe.close(() => r()));
  const settings = JSON.parse(await readFile(join(configDir, "config.json"), "utf8"));
  settings.server.port = port;
  await writeFile(join(configDir, "config.json"), JSON.stringify(settings));
  await run("config", "validate");
  const child = spawn(process.execPath, [cli, "--config-dir", configDir, "serve"], { cwd, env, stdio: ["ignore", "pipe", "pipe"] });
  let diagnostics = ""; child.stdout.on("data", b => { diagnostics += b; }); child.stderr.on("data", b => { diagnostics += b; });
  t.after(async () => { if (child.exitCode === null) { child.kill("SIGTERM"); await once(child, "exit"); } });
  const deadline = Date.now() + 30000;
  while (!diagnostics.includes("MissionControl: ")) {
    if (child.exitCode !== null || Date.now() > deadline) throw new Error(`Controller failed to start: ${diagnostics}`);
    await new Promise(r => setTimeout(r, 50));
  }
  const unauthenticated = await fetch(`http://127.0.0.1:${port}/api/v1/goals`); assert.equal(unauthenticated.status, 401);
  const descriptionFile = initialized.example.goalFile;
  const credentialFile=join(secrets,"synthetic-agent");
  const access=JSON.parse((await run("access","create","builder","--project","synthetic","--permissions","goals:read,goals:create","--token-file",credentialFile)).stdout);
  assert.equal(access.policy.id,"builder"); assert.equal(access.token,undefined);
  await assert.rejects(run("access","create","outside","--project","synthetic","--token-file",join(root,"outside-token")));
  const draft=JSON.parse((await run("goal","draft","--project","synthetic","--input",descriptionFile,"--token-file",credentialFile)).stdout);
  assert.equal(draft.valid,true);
  await assert.rejects(run("goal","create","--project","synthetic","--input",descriptionFile,"--token-file",credentialFile));
  const scopedGoal=JSON.parse((await run("goal","create","--project","synthetic","--input",descriptionFile,"--token-file",credentialFile,"--idempotency-key","scoped-install-test")).stdout);
  assert.equal(scopedGoal.config.projectId,"synthetic");
  await run("access","revoke","builder");
  await assert.rejects(run("goal","inspect",scopedGoal.id,"--token-file",credentialFile));
  const goal = JSON.parse((await run("goal", "create", "--project", "synthetic", "--input", descriptionFile, "--idempotency-key", "install-test")).stdout);
  const repeat = JSON.parse((await run("goal", "create", "--project", "synthetic", "--input", descriptionFile, "--idempotency-key", "install-test")).stdout); assert.equal(repeat.id, goal.id);
  let current;
  do {
    current = JSON.parse((await run("goal", "inspect", goal.id)).stdout);
    if (["failed", "cancelled"].includes(current.goal.status)) throw new Error(`Synthetic workflow failed: ${JSON.stringify(current)}`);
    if (current.goal.status === "completed") break;
    await new Promise(r => setTimeout(r, 150));
  } while (Date.now() < deadline);
  assert.equal(current.goal.status, "completed", JSON.stringify(current));
  const originalHash = current.goal.config.admission.configurationHash;
  const projectPath = join(configDir, "projects/synthetic.json");
  const project = JSON.parse(await readFile(projectPath, "utf8"));
  project.name = "Updated synthetic project";
  await writeFile(projectPath, JSON.stringify(project));
  const activated = JSON.parse((await run("config", "apply")).stdout);
  assert.notEqual(activated.hash, originalHash);
  assert.equal(JSON.parse((await run("goal", "inspect", goal.id)).stdout).goal.config.admission.configurationHash, originalHash);
  assert.equal(JSON.parse((await run("project", "list")).stdout)[0].name, project.name);
  assert.equal(current.tasks.length, 1); assert.equal(current.tasks[0].status, "accepted");
  assert.deepEqual(await readdir(cwd), []);
  const databases = (await readdir(state)).filter(n => n.endsWith(".db")); assert.deepEqual(databases, ["mission-control.db"]);
  const identityFile=join(root,"age-identity.txt"),recipientFile=join(root,"age-recipient.txt"),backupFile=join(root,"complete.age");
  await exec("age-keygen",["-o",identityFile]);
  await writeFile(recipientFile,(await exec("age-keygen",["-y",identityFile])).stdout);
  const backup=JSON.parse((await run("backup","create","--complete","--destination",backupFile,"--recipient-file",recipientFile)).stdout);
  assert.equal(backup.complete,true);assert.ok(backup.files.some((f:any)=>f.path.endsWith("report.json")));
  child.kill("SIGTERM"); await once(child, "exit"); assert.equal(child.exitCode, 0);
  const restored=join(root,"restored");await run("restore","--input",backupFile,"--identity-file",identityFile,"--destination",restored);
  const restoredConfig=JSON.parse(await readFile(join(configDir,"config.json"),"utf8"));restoredConfig.stateDir=restored;await writeFile(join(configDir,"config.json"),JSON.stringify(restoredConfig));
  await assert.rejects(run("serve")); // refuses the original snapshot roots
  await run("config","apply","--offline");assert.equal(JSON.parse((await run("state","inspect")).stdout).integrity[0],"ok");
});
